# system('dropdb munchwins')
# system('createdb munchwins')
system('psql munchwins < schema.sql')
# system('psql munchwins < kv.sql')
# system("heroku pg:psql #{ENV["DATABASE_URL"]} < schema.sql")
# system("heroku pg:psql #{ENV["DATABASE_URL"]} < kv.sql")